 ---
 joinmessage1: "&c=========================="
 joinmessage2: "&dWelcome to DarkRealmsPvP || Vote with /vote"
 joinmessage3: "&dJoin our forums DaekRealms.cf"
 joinmessage4: "&c=========================="
 ...
